# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    before: |
      # Installing terraform
      nix-env -iA nixpkgs.terraform
    init: |
      # Init terraform modules
      terraform init
    command: |
      echo 'You can now run "terraform apply"'

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
